name: game-of-life
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: GameOfLife
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - game-of-life
      - hspec
