name: Test Solutions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-solutions:
    runs-on: ubuntu-latest
    container: ghcr.io/yogan/yogans-advent-of-code:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mark workspace as safe for git clean
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          df -h | grep root > /disk_space.log

      - name: AWK - test solutions
        run: ./bin/test-awk.sh
        if: success() || failure()

      - name: AWK - cleanup
        run: |
          git clean -fxd
          echo "AWK done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Bash - test solutions
        run: ./bin/test-bash.sh
        if: success() || failure()

      - name: Bash - cleanup
        run: |
          git clean -fxd
          echo "Bash done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Clojure - test solutions
        run: ./bin/test-clojure.sh
        if: success() || failure()

      - name: Clojure - cleanup
        run: |
          git clean -fxd
          echo "Clojure done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Common LISP - test solutions
        run: ./bin/test-common-lisp.sh
        if: success() || failure()

      - name: Common LISP - cleanup
        run: |
          git clean -fxd
          echo "Common LISP done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Crystal - test solutions
        run: ./bin/test-crystal.sh
        if: success() || failure()

      - name: Crystal - cleanup
        run: |
          git clean -fxd
          echo "Crystal done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: C - test solutions
        run: ./bin/test-c.sh
        if: success() || failure()

      - name: C - cleanup
        run: |
          git clean -fxd
          echo "C done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: C++ - test solutions
        run: ./bin/test-cpp.sh
        if: success() || failure()

      - name: C++ - cleanup
        run: |
          git clean -fxd
          echo "C++ done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: C# - test solutions
        run: ./bin/test-dotnet.sh csharp
        if: success() || failure()

      - name: C# - cleanup
        run: |
          git clean -fxd
          echo "C# done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Elixir - test solutions
        run: ./bin/test-elixir.sh
        if: success() || failure()

      - name: Elixir - cleanup
        run: |
          git clean -fxd
          echo "Elixir done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Elm - test solutions
        run: ./bin/test-elm.sh
        if: success() || failure()

      - name: Elm - cleanup
        run: |
          git clean -fxd
          echo "Elm done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Fortran - test solutions
        run: ./bin/test-fortran.sh
        if: success() || failure()

      - name: Fortran - cleanup
        run: |
          git clean -fxd
          echo "Fortran done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: F# - test solutions
        run: ./bin/test-dotnet.sh fsharp
        if: success() || failure()

      - name: F# - cleanup
        run: |
          git clean -fxd
          echo "F# done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Gleam - test solutions
        run: ./bin/test-gleam.sh
        if: success() || failure()

      - name: Gleam - cleanup
        run: |
          git clean -fxd
          echo "Gleam done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Go - test solutions
        run: ./bin/test-go.sh
        if: success() || failure()

      - name: Go - cleanup
        run: |
          git clean -fxd
          echo "Go done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Groovy - test solutions
        run: ./bin/test-groovy.sh
        if: success() || failure()

      - name: Groovy - cleanup
        run: |
          git clean -fxd
          echo "Groovy done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Haskell - test solutions
        run: ./bin/test-haskell.sh
        if: success() || failure()

      - name: Haskell - cleanup
        run: |
          git clean -fxd
          echo "Haskell done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Java - test solutions
        run: ./bin/test-java.sh
        if: success() || failure()

      - name: Java - cleanup
        run: |
          git clean -fxd
          echo "Java done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: JavaScript - test solutions
        run: ./bin/test-javascript.sh
        if: success() || failure()

      - name: JavaScript - cleanup
        run: |
          git clean -fxd
          echo "JavaScript done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Julia - test solutions
        run: ./bin/test-julia.sh
        if: success() || failure()

      - name: Julia - cleanup
        run: |
          git clean -fxd
          echo "Julia done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Kotlin - test solutions
        run: ./bin/test-kotlin.sh
        if: success() || failure()

      - name: Kotlin - cleanup
        run: |
          git clean -fxd
          echo "Kotlin done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: MIPS Assembly - test solutions
        run: ./bin/test-mips.sh
        if: success() || failure()

      - name: MIPS Assembly - cleanup
        run: |
          git clean -fxd
          echo "MIPS done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Nim - test solutions
        run: ./bin/test-nim.sh
        if: success() || failure()

      - name: Nim - cleanup
        run: |
          git clean -fxd
          echo "Nim done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Perl - test solutions
        run: ./bin/test-perl.sh
        if: success() || failure()

      - name: Perl - cleanup
        run: |
          git clean -fxd
          echo "Perl done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: PowerShell - test solutions
        run: ./bin/test-powershell.sh
        if: success() || failure()

      - name: PowerShell - cleanup
        run: |
          git clean -fxd
          echo "PowerShell done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Python - test solutions
        run: ./bin/test-python.sh
        if: success() || failure()

      - name: Python - cleanup
        run: |
          git clean -fxd
          echo "Python done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: R - test solutions
        run: ./bin/test-r.sh
        if: success() || failure()

      - name: R - cleanup
        run: |
          git clean -fxd
          echo "R done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Ruby - test solutions
        run: ./bin/test-ruby.sh
        if: success() || failure()

      - name: Ruby - cleanup
        run: |
          git clean -fxd
          echo "Ruby done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Rust - test solutions
        run: ./bin/test-rust.sh
        if: success() || failure()

      - name: Rust - cleanup
        run: |
          git clean -fxd
          echo "Rust done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Scala - test solutions
        run: ./bin/test-scala.sh
        if: success() || failure()

      - name: Scala - cleanup
        run: |
          git clean -fxd
          echo "Scala done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Standard ML - test solutions
        run: ./bin/test-sml.sh
        if: success() || failure()

      - name: Standard ML - cleanup
        run: |
          git clean -fxd
          echo "Standard ML done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Swift - test solutions
        run: ./bin/test-swift.sh
        if: success() || failure()

      - name: Swift - cleanup
        run: |
          git clean -fxd
          echo "Swift done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Tcl - test solutions
        run: ./bin/test-tcl.sh
        if: success() || failure()

      - name: Tcl - cleanup
        run: |
          git clean -fxd
          echo "Tcl done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: TypeScript - test solutions
        run: ./bin/test-typescript.sh
        if: success() || failure()

      - name: TypeScript - cleanup
        run: |
          git clean -fxd
          echo "TypeScript done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Zig - test solutions
        run: ./bin/test-zig.sh
        if: success() || failure()

      - name: Zig - cleanup
        run: |
          git clean -fxd
          echo "Zig done" >> /disk_space.log
          df -h | grep root | tee -a /disk_space.log
        if: success() || failure()

      - name: Print disk space log
        run: cat /disk_space.log
        if: success() || failure()
