name: Test Solutions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # run every night at 2:42 UTC (3:42/4:42 German time)
    - cron: "42 3 * * *"

# Grant the GITHUB_TOKEN read permission to allow the `prepare-test-matrix` job to
# get a list of changed files from the Git history.
permissions:
  contents: read

jobs:
  prepare-test-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history to ensure a correct diff against the base branch
          fetch-depth: 0

      - name: Prepare test matrix
        id: prepare
        # Pass the event type to the script for conditional logic.
        run: echo "matrix=$(./bin/prepare-matrix.sh '${{ github.event_name }}' '${{ github.base_ref }}' '${{ github.ref_name }}')" >> "$GITHUB_OUTPUT"

  test-solutions:
    runs-on: ubuntu-latest
    container: ghcr.io/yogan/yogans-advent-of-code:latest
    needs: prepare-test-matrix

    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(needs.prepare-test-matrix.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mark workspace as safe for git clean
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Increase disk space by deleting unnecessary stuff
        run: |
          df -h | grep root | awk '{print "Free space (initial): " $4}' | tee -a /disk_space.log
          rm -rf /__t/CodeQL /__t/Python /__t/PyPy /__t/node /__t/go /__t/Ruby
          df -h | grep root | awk '{print "Free space (after cleanup): " $4}' | tee -a /disk_space.log

      - name: "Test solutions for ${{ matrix.language }}"
        run: ./bin/test.sh "${{ matrix.language }}"
        if: always()

      - name: "Cleanup for ${{ matrix.language }}"
        run: ./bin/cleanup.sh "${{ matrix.language }}" /disk_space.log
        if: always()

      - name: Print disk space log
        run: cat /disk_space.log
        if: always()
