name: Test Solutions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-solutions:
    runs-on: ubuntu-latest
    container: ghcr.io/yogan/yogans-advent-of-code:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Clojure solutions
        run: ./bin/test-clojure.sh

      - name: Test Common LISP solutions
        run: ./bin/test-common-lisp.sh

      - name: Test Crystal solutions
        run: ./bin/test-crystal.sh

      - name: Test C++ solutions
        run: ./bin/test-cpp.sh

      - name: Test C# solutions
        run: ./bin/test-dotnet.sh csharp

      - name: Test Elixir solutions
        run: ./bin/test-elixir.sh

      - name: Test F# solutions
        run: ./bin/test-dotnet.sh fsharp

      - name: Test JavaScript solutions
        run: ./bin/test-javascript.sh

      - name: Test Julia solutions
        run: ./bin/test-julia.sh

      - name: Test Kotlin solutions
        run: ./bin/test-kotlin.sh

      - name: Test MIPS Assembly solutions
        run: ./bin/test-mips.sh

      - name: Test Nim solutions
        run: ./bin/test-nim.sh

      - name: Test Python solutions
        run: ./bin/test-python.sh
