name: Test Solutions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # run every night at 2:42 UTC (3:42/4:42 German time)
    - cron: '42 3 * * *'

# Grant the GITHUB_TOKEN read permission to allow the `prepare-test-matrix` job to
# get a list of changed files from the Git history.
permissions:
  contents: read

jobs:
  prepare-test-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history to ensure a correct diff against the base branch
          fetch-depth: 0

      - name: Prepare test matrix
        id: prepare
        run: echo "matrix=$(./bin/prepare-matrix.sh '${{ github.event_name }}' '${{ github.base_ref }}')" >> "$GITHUB_OUTPUT"

  test-solutions:
    runs-on: ubuntu-latest
    container: ghcr.io/yogan/yogans-advent-of-code:latest
    needs: prepare-test-matrix

    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(needs.prepare-test-matrix.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Test solutions for ${{ matrix.language }}'
        run: ./bin/test.sh "${{ matrix.language }}"
        if: always()
