name: Test Solutions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # run every night at 2:42 UTC (3:42/4:42 German time)
    - cron: "42 3 * * *"

jobs:
  test-solutions:
    runs-on: ubuntu-latest
    container: ghcr.io/yogan/yogans-advent-of-code:latest

    strategy:
      fail-fast: false
      matrix:
        language:
          - AWK
          - Bash
          - Clojure
          - "Common LISP"
          - Crystal
          - C
          - "C++"
          - "C#"
          - Elixir
          - Elm
          - Erlang
          - Fortran
          - "F#"
          - Gleam
          - Go
          - Groovy
          - Haskell
          - Java
          - JavaScript
          - Julia
          - Kotlin
          - "MIPS Assembly"
          - Nim
          - Perl
          - PowerShell
          - Prolog
          - Python
          - R
          - Ruby
          - Rust
          - Scheme
          - Scala
          - "Standard ML"
          - Swift
          - Tcl
          - TypeScript
          - WebAssembly
          - Zig

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mark workspace as safe for git clean
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Increase disk space by deleting unnecessary stuff
        run: |
          df -h | grep root | awk '{print "Free space (initial): " $4}' | tee -a /disk_space.log
          rm -rf /__t/CodeQL /__t/Python /__t/PyPy /__t/node /__t/go /__t/Ruby
          df -h | grep root | awk '{print "Free space (after cleanup): " $4}' | tee -a /disk_space.log

      - name: "Test solutions for ${{ matrix.language }}"
        run: |
          language="${{ matrix.language }}"

          # Special handling for languages with different test scripts
          case "$language" in
            "C#")
              ./bin/test-dotnet.sh csharp
              ;;
            "F#")
              ./bin/test-dotnet.sh fsharp
              ;;
            "MIPS Assembly")
              ./bin/test-mips.sh
              ;;
            *)
              # Default case for most languages
              # Convert the language name to a lowercase file name
              sanitized_language=$(echo "$language" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')
              ./bin/test-"$sanitized_language".sh
              ;;
          esac
        if: always()

      - name: "Cleanup for ${{ matrix.language }}"
        run: ./bin/cleanup.sh "${{ matrix.language }}" /disk_space.log
        if: always()

      - name: Print disk space log
        run: cat /disk_space.log
        if: always()
